### PR TITLE
Optimize check for autoloader / resolve issue #7

### PR DESCRIPTION
**Pull request by CDRO**
https://github.com/franzholz/div2007/issues/7

This issue is solved by this

### CODE REVIEW

**Comment by franzholz** [comment]
The support for TYPO3 7.x cannot be dropped at this moment and for the next 2 years.

You have modified the check about the TYPO3 version:

     if (class_exists(\TYPO3\CMS\Rtehtmlarea\Controller\Wizard\RteController::class) || version_compare(TYPO3_version, '8.0.0', '>=')) { 

However it is not necessary to install rtehtmlarea or rte. So this check will fail in some cases.

**Comment by CDRO** [comment]
Ok, but with a version 2.0.0 in the master branch and 1.x in a separate branch, both can be supplied.

I've seen your point about rtehtmlarea and you're absolutely right. At this point I'm not sure if it is possible to know in what version we are working by checking the classes available :-/

**Comment by CDRO** [comment]
I'd like to propse the following:
- new branch 1.x where the current 1.9.x is maintained (and maybe 1.10.x later on)
- the master holds a version 2.0.0 which breaks (and this should be absolutely fine according to semver) in order to ensure that div2007 is installable using composer

Alternatively, there should be a way to determine if we're in V8 without having to use the constant that we could try. I'll give it some thought and come back to you with an idea, if that is ok.

**Comment by franzholz** [comment]
It would be a drawback to have a separate branch for TYPO3 7.x, because then I have more work to do. And users as well have to decide which version of div2007 to install. So a solution must be found to have support for 7.x and 8.x in the same extension version.

**Comment by franzholz** [comment]
I have asked this question now at 
https://stackoverflow.com/questions/50109006/determine-the-typo3-version-in-migrations-classes-for-the-composer

**Comment by franzholz** [comment]
The solution is now due to your proposal:

The class alias mapper has been removed from div2007 and it is now in the new extension migration_core.

**Comment by CDRO** [comment]
Perfect, you're the best, I think that this is absolutely the way to go!

**Pull request closed without merging**
